name: Publish HTML

on:
  schedule:
    - cron: '0 0 * * *'  # Her gece 00:00'da çalışacak

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4

    - name: Set up ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
        unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
        sudo apt-get install -y chromium-browser

    - name: Run Python script
      run: python WWE.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
